routes/web.php
            Route::resource('batch', 'BatchController');

            Route::resource('refundpolicy', 'RefundPolicyController');
            Route::resource('refundorder', 'RefundController');

            Route::get('admin/coloroption', 'ColorOptionController@index')->name('coloroption.view');
            Route::post('admin/coloroption/update', 'ColorOptionController@update')->name('coloroption.update');
            Route::get('admin/coloroption/reset', 'ColorOptionController@reset')->name('coloroption.reset');

            Route::get('database/backup', 'DatabaseController@index')->name('database.backup');
            Route::post('database/genrate', 'DatabaseController@genrate')->name('database.genrate');
            Route::post('database/delete', 'DatabaseController@deletebackup')->name('database.delete');

            Route::get('database/download/{filename}', 'DatabaseController@download')->name('database.download');
            Route::post('database/dump', 'DatabaseController@update')->name('database.dump');

            Route::resource('advertisement','AdvertisementController');

            Route::resource('manualpayment','ManualPaymentController');

            Route::get('order/enroll/{user_id}', 'OrderController@enrollUser')->name('order.enrolluserview');


            Route::resource('attandance','AttandanceController');
            Route::get('view/users/{id}', 'AttandanceController@enrolled')->name('enrolled.users');
            Route::get('user/attandance/{id}/{course}', 'AttandanceController@attandance')->name('user.attandance');

            Route::get('/admin/push-notifications','OneSignalNotificationController@index')->name('onesignal.settings');
            Route::post('/admin/onesignal/keys','OneSignalNotificationController@updateKeys')->name('onesignal.update');
            Route::post('/admin/push-notifications','OneSignalNotificationController@push')->name('admin.push.notif');


            Route::get('/admin/import/quiz', 'QuizController@importquiz')->name('import.quiz');
            Route::post('admin/import', 'QuizController@import')->name('import');


            Route::get('quick/update', 'ReplaceFilesController@index')->name('quick.update');
            Route::post('replace', 'ReplaceFilesController@replace')->name('replace');

            Route::get('twilio/settings','TwilioController@index')->name('twilio.settings');
            Route::post('twilio/update','TwilioController@update')->name('twilio.update');


            Route::get('activity/users','UserActivityController@index')->name('activity.index');
            Route::post('activity/delete/{id}','UserActivityController@delete')->name('activity.delete');

            Route::get('remove/public','SupportController@index')->name('remove.public');
            Route::post('add/content','SupportController@addcontent')->name('add.content');
            Route::post('create/file','SupportController@createfile')->name('create.file');

            Route::resource('subscription/plan','InstructorPlanController');
            Route::resource('orders/subscription', 'SubscribedOrdersController');

            Route::get('quiz/review', 'QuizController@quizreview')->name('quiz.review');
            Route::post('quizreview/approve/{id}', 'QuizController@quizreviewQuick')->name('quizreview.quick');

            Route::resource('directory','SeoDirectoryController');
            Route::get('/directory/show/{id}/{city}', 'SeoDirectoryController@view')->name('directory.view');

            Route::resource('previous-paper','PreviousPaperController');

            Route::resource('private-course','PrivateCourseController');
            Route::resource('meeting-recordings','MeetingRecordingController');

            Route::get('plan/subscribe/settings', 'SubscriptionEnableController@view')->name('plan.settings');
            Route::post('plan/subscribe/update', 'SubscriptionEnableController@settings')->name('plan.settings.update');



            // ======== googlemeet start =============================
            Route::prefix('googlemeet')->group(function (){

                Route::get('dashboard','GoogleMeetController@dashboard')->name('googlemeet.index');
                Route::get('create/meeting','GoogleMeetController@create')->name('googlemeet.meeting.create');
                Route::post('store/new/meeting','GoogleMeetController@store')->name('googlemeet.store');
                Route::delete('delete/meeting/{id}','GoogleMeetController@delete')->name('googlemeet.delete');
                Route::get('edit/meeting/{meetingid}','GoogleMeetController@edit')->name('googlemeet.edit');
                Route::post('update/meeting/{meetingid}','GoogleMeetController@updatemeeting')->name('googlemeet.update');
                Route::post('googlement-token/update','GoogleMeetController@googleupdatefile')->name('googlemeet.updatefile');
            });

            Route::get('setting','GoogleMeetController@googlemeetsetting')->name('googlemeet.setting');
            Route::get('setting','GoogleMeetController@googlemeetsetting')->name('googlemeet.setting');
            Route::get('oauth', ['as' => 'oauthCallback', 'uses' => 'GoogleMeetController@oauth']);

            Route::get('googlemeet/allmeeting', 'GoogleMeetController@allgooglemeeting')->name('googlemeet.allgooglemeeting');
            // ======== googlemeet end ===============================

            Route::get('/admin/addon', 'AddonController@addon')->name('admin.addon');
            Route::get('/admin/add/addon', 'AddonController@addaddon')->name('add.addon');
            Route::post('/admin/install/addon', 'AddonController@installaddon')->name('install.addon');
            Route::post('/admin/addon/status/{module}', 'AddonController@status')->name('status.addon');
            Route::post('/admin/addon/delete/{module}', 'AddonController@delete')->name('addon.delete');



            Route::get('/admin/revenue/report', 'RevenueReportController@report')->name('admin.revenue.report');
            Route::get('/revenue/report/instructor', 'RevenueReportController@instructorReport')->name('instructor.revenue.report');

        });

        Route::middleware(['admin_instructor', 'IsInstalled'])->group(function () {

        
            try {
                \DB::connection()->getPdo();

                if(\DB::connection()->getDatabaseName() && Schema::hasTable('settings')){
                    if(env('IS_INSTALLED') == 1){
                        $vod = Setting::first();
                        
                        if(isset($vod) && $vod->zoom_enable == 1){
                            
                            Route::prefix('zoom')->group(function (){
                                Route::get('setting','ZoomController@setting')->name('zoom.setting');
                                Route::get('dashboard','ZoomController@dashboard')->name('zoom.index');
                                Route::post('token/update','ZoomController@updateToken')->name('updateToken');
                                Route::get('create/meeting','ZoomController@create')->name('meeting.create');
                                Route::delete('delete/meeting/{id}','ZoomController@delete')->name('zoom.delete');
                                Route::post('store/new/meeting','ZoomController@store')->name('zoom.store');
                                Route::get('edit/meeting/{meetingid}','ZoomController@edit')->name('zoom.edit');
                                Route::post('update/meeting/{meetingid}','ZoomController@updatemeeting')->name('zoom.update');
                                Route::get('show/meeting/{meetingid}','ZoomController@show')->name('zoom.show');
                            });
                        }

                        if(isset($vod) && $vod->bbl_enable == 1){
                            Route::prefix('bigblue')->group(function (){
                                Route::view('setting','bbl.setting')->name('bbl.setting');
                                Route::post('setting','BigBlueController@setting')->name('bbl.update.setting');
                                Route::get('meetings','BigBlueController@index')->name('bbl.all.meeting');
                                Route::view('meeting/create','bbl.create')->name('bbl.create');
                                Route::post('meeting/store','BigBlueController@store')->name('bbl.store');
                                Route::get('meeting/edit/{meetingid}','BigBlueController@edit')->name('bbl.edit');
                                Route::post('meeting/update/{meetingid}','BigBlueController@update')->name('bbl.update');
                                Route::delete('meeting/delete/{id}','BigBlueController@delete')->name('bbl.delete');
                                Route::get('api/create/meeting/{id}','BigBlueController@apiCreate')->name('api.create.meeting');

                                
                            });
                        }
                    }
                }
            }
            catch(\Exception $ex){

              return redirect('/get/step2');
            }

            // ====== jisti meeting start ==========
            Route::get('jitsi-dashboard', 'JitsiController@jitsidashboard')->name('jitsi.dashboard');
            Route::get('jitsi-create', 'JitsiController@jitsicreate')->name('jitsi.create');
            Route::post('jitsi-meeting-save', 'JitsiController@savejitsimeeting')->name('jitsi.meeting.save');
            Route::delete('delete-meeting/{id}', 'JitsiController@deletemeeting')->name('deletemeeting.jitsi');
            // ====== jisti meeting end =============


            Route::prefix('user')->group(function (){
              Route::get('edit/{id}','UserController@edit')->name('user.edit');
              Route::put('/edit/{id}','UserController@update')->name('user.update');
            });

            Route::resource('category','CategoriesController');

resources/views/admin/directory/create.blade.php
@extends('admin/layouts.master')
@section('title', 'Add Directory - Admin')
@section('body')


<section class="content">
  @include('admin.message')
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title"> {{ __('adminstaticword.Add') }} {{ __('adminstaticword.Directory') }}</h3>
        </div>
        <div class="box-body">
          <div class="form-group">
            <form id="demo-form2" method="post" action="{{url('directory/')}}" data-parsley-validate class="form-horizontal form-label-left" enctype="multipart/form-data">
              {{ csrf_field() }}
                      
           
              <div class="row">
                <div class="col-md-6">
                  <label for="exampleInputTit1e">{{ __('adminstaticword.City') }}:<sup class="redstar">*</sup></label>
                  <input class="form-control" type="text" name="city" placeholder="{{ __('adminstaticword.Enter') }} {{ __('adminstaticword.City') }}">
                </div>
                {{-- <div class="col-md-6">
                  <label for="exampleInputSlug">{{ __('adminstaticword.SubHeading') }}:<sup class="redstar">*</sup></label>
                  <input type="slug" class="form-control" name="sub_heading" id="exampleInputPassword1" placeholder="Please Enter Your Sub Heading">
                </div> --}}
              </div>
              <br>

              <div class="row">
               
                <div class="col-md-12">
                  <label for="exampleInputDetails">{{ __('adminstaticword.Detail') }}:<sup class="redstar">*</sup></label>
                  <textarea name="detail" id="detail" rows="1" class="form-control" placeholder="{{ __('adminstaticword.Enter') }} {{ __('adminstaticword.Detail') }}"></textarea>
                </div>
              </div>
              <br>

             

              <div class="row">
                <div class="col-md-4">
                  <label for="exampleInputDetails">{{ __('adminstaticword.Status') }}:</label>
                  <br>
                  <li class="tg-list-item">              
                    <input class="tgl tgl-skewed" id="status" type="checkbox" name="status" >
                    <label class="tgl-btn" data-tg-off="{{ __('adminstaticword.Disable') }}" data-tg-on="{{ __('adminstaticword.Enable') }}" for="status"></label>
                  </li>
                  <input type="hidden"  name="free" value="0" for="status" id="status">
                </div>

                
              </div>
              <br>
              <br>
      
              <div class="box-footer">
                <button type="submit" value="Add Slider" class="btn btn-md col-md-2 btn-primary">{{ __('adminstaticword.Save') }}</button>
              </div>
         
            </form>
          </div>
        </div>
        <!-- /.box -->
      </div>
      <!-- /.box -->
    </div>
    <!--/.col (right) -->
  </div>
  <!-- /.row -->
</section> 
@endsection

resources/views/admin/directory/edit.blade.php
@extends('admin/layouts.master')
@section('title', 'Edit Directory - Admin')
@section('body')

<section class="content">
  @include('admin.message')
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title"> {{ __('adminstaticword.Edit') }} {{ __('adminstaticword.Directory') }}</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <div class="form-group">
            <form id="demo-form" method="post"  action="{{url('directory/'.$show->id)}}
              "data-parsley-validate class="form-horizontal form-label-left" enctype="multipart/form-data">
              {{ csrf_field() }}
              {{ method_field('PUT') }}
           

              <div class="row">
                <div class="col-md-6">
                  <label for="exampleInputTit1e">{{ __('adminstaticword.City') }}:<sup class="redstar">*</sup></label>
                  <input type="text" class="form-control" name="heading" id="exampleInputTitle" value="{{$show->city}}">
                </div>
          
               
              </div>
              <br> 

              <div class="row">
               
                <div class="col-md-12">
                  <label for="exampleInputTit1e">{{ __('adminstaticword.Detail') }}:<sup class="redstar">*</sup></label>
                  <textarea type="text" id="detail" class="form-control" name="detail" id="exampleInputTitle">{{$show->detail}}</textarea>
                </div>
              </div>
              <br> 

              <div class="row">
                
                <div class="col-md-4">
                  <label for="exampleInputTit1e">{{ __('adminstaticword.Status') }}:</label>
                  <li class="tg-list-item">              
                    <input class="tgl tgl-skewed" id="status" type="checkbox" name="status" {{ $show->status == '1' ? 'checked' : '' }} >
                    <label class="tgl-btn" data-tg-off="{{ __('adminstaticword.Disable') }}" data-tg-on="{{ __('adminstaticword.Enable') }}" for="status"></label>
                  </li>
                  <input type="hidden"  name="free" value="0" for="status" id="status">
                </div>


                


              </div>
              <br> 
           
              <div class="box-footer">
                <button type="submit" class="btn btn-lg col-md-2 btn-primary">+ {{ __('adminstaticword.Save') }}</button>
              </div>
            </form>
          </div>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!--/.col -->
  </div>
</section>

@endsection

resources/views/admin/directory/index.blade.php
@extends('admin/layouts.master')
@section('title', 'Directory - Admin')
@section('body')

<section class="content">

  @include('admin.message')
<div class="row">
  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">{{ __('adminstaticword.Directory') }}</h3>
        <a class="btn btn-info btn-sm" href="{{url('directory/create')}}">
          <i class="glyphicon glyphicon">+</i> {{ __('adminstaticword.Add') }} {{ __('adminstaticword.Directory') }}
        </a>
      </div>
      <!-- /.box-header -->
        <div class="box-body">
          <div class="table-responsive">
            <table id="example1" class="table table-bordered table-striped">

              <thead>

                <tr>
                  <th>#</th>
                  <th>{{ __('adminstaticword.City') }}</th>
                  <th>{{ __('adminstaticword.Detail') }}</th>
                  <th>{{ __('adminstaticword.Status') }}</th>
                  <th>{{ __('adminstaticword.Edit') }}</th>
                  <th>{{ __('adminstaticword.Delete') }}</th>
                  <th>{{ __('adminstaticword.View') }}</th>
                </tr>
              </thead>

              <tbody>
                <?php $i=0;?>
                 
                    @foreach($directory as $dir)
                      <?php $i++;?>
                      <tr>
                        <td><?php echo $i;?></td>
                        <td>{{ $dir->city }}</td>
                        <td>{!! $dir->detail !!}</td>
                        <td>
                            @if($dir->status ==1)
                              {{ __('adminstaticword.Active') }}
                            @else
                              {{ __('adminstaticword.Deactive') }}
                            @endif
                        </td>

                        <td>
                          <a class="btn btn-success btn-sm" href="{{ route('directory.show',$dir->id) }}">
                          <i class="glyphicon glyphicon-pencil"></i></a>
                        </td>

                        <td>
                          <form  method="post" action="{{url('directory/'.$dir->id)}}
                            "data-parsley-validate class="form-horizontal form-label-left">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button onclick="return confirm('Are you sure you want to delete?')"  type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash-o"></i></button>
                          </form>
                        </td>

                        <td>
                          <a class="btn btn-success btn-sm" target="blank" href="{{ route('directory.view',['id' => $dir->id, 'city' => str_slug(str_replace('-','&',$dir->city))]) }}">
                          {{ __('adminstaticword.View') }}</a>
                        </td>
                      </tr>
                    @endforeach
                 
              </tbody>
            </table>
          </div>
        </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
  <!-- /.col -->
</div>


</section>

@endsection